#!/usr/bin/env bash
# Reclaim disk from local build artifacts. The Rust target/ dir grows huge (~15-18G)
# and Docker build cache piles up. SAFE: never touches Docker volumes (your DB data)
# or the source tree — only regenerable build output.
#   bash scripts/disk-cleanup.sh
# Tip: run it periodically (e.g. weekly cron):
#   (crontab -l 2>/dev/null; echo "0 3 * * 0 cd $(pwd) && bash scripts/disk-cleanup.sh >> /tmp/lm-cleanup.log 2>&1") | crontab -
set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

free() { df -h . | awk 'NR==2{print $4" free ("$5" used)"}'; }
echo "before: $(free)"

# 1) Rust build output (biggest; fully regenerated by the next `cargo build`).
if [ -d target ]; then
  echo "→ cargo clean"
  cargo clean 2>/dev/null || rm -rf target
fi

# 2) Docker build cache + dangling images — NOT volumes, NOT running containers.
#    `docker builder prune` / `image prune` never remove named volumes (your DB).
if docker info >/dev/null 2>&1; then
  echo "→ docker builder prune"
  docker builder prune -f >/dev/null 2>&1 || true
  echo "→ docker image prune (dangling)"
  docker image prune -f >/dev/null 2>&1 || true
else
  echo "→ docker not running — skipped (volumes/DB untouched either way)"
fi

# 3) Stray release tarballs left in the repo root.
rm -f last-monitor-*.tar.gz 2>/dev/null || true

echo "after:  $(free)"
echo "OK — cleanup done"
