#!/usr/bin/env bash
# Squash migrations into a single consolidated 0001 per database, for a FRESH v3 GA DB.
# Safe by construction: the config 0001 is generated from a pg_dump of the schema that
# the FULL old migration chain produces, then re-applied and schema-diffed to prove it
# reproduces that schema exactly. The data 0001 (hand-authored, TimescaleDB hypertables
# don't pg_dump cleanly) is verified by comparing columns/indexes/hypertables old-vs-new.
# On PASS it swaps the repo's migrations in place. Throwaway containers; self-cleaning.
#
# NOT for existing databases — this resets migration history (fresh installs only).
#   bash scripts/squash-migrations.sh
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
STAGE="${SQUASH_STAGE:-$REPO/../$(basename "$REPO")-squash-stage}"; STAGE="/tmp/vantage-squash-$$"
DATA_STAGED="${DATA_STAGED:-$(dirname "$0")/../.squash/data_0001.sql}"
CFG_IMG="postgres:16.6-alpine"
TS_IMG="timescale/timescaledb:2.17.2-pg16"
mkdir -p "$STAGE"
CIDS=()
cleanup() { for c in "${CIDS[@]:-}"; do docker rm -f "$c" >/dev/null 2>&1 || true; done; rm -rf "$STAGE"; }
trap cleanup EXIT

start_pg() { # <image> <db>  -> echoes container id
  local img="$1" db="$2" cid; cid="vantage-sq-$RANDOM"
  docker run -d --name "$cid" -e POSTGRES_USER=vantage -e POSTGRES_PASSWORD=vantage -e POSTGRES_DB="$db" "$img" >/dev/null
  CIDS+=("$cid")
  local ok=0
  for _ in $(seq 1 90); do
    if docker exec "$cid" psql -tAqX -U vantage -d "$db" -c "SELECT 1" >/dev/null 2>&1; then ok=$((ok+1)); [ "$ok" -ge 4 ] && break; else ok=0; fi
    sleep 1
  done
  echo "$cid"
}
apply() { # <cid> <db> <dir-or-file>
  local cid="$1" db="$2" src="$3" f
  if [ -d "$src" ]; then
    for f in "$src"/*.sql; do docker exec -i "$cid" psql -v ON_ERROR_STOP=1 -q -U vantage -d "$db" < "$f" >/dev/null; done
  else
    docker exec -i "$cid" psql -v ON_ERROR_STOP=1 -q -U vantage -d "$db" < "$src" >/dev/null
  fi
}

echo "════════ CONFIG DB ════════"
c1=$(start_pg "$CFG_IMG" vantage_config)
apply "$c1" vantage_config "$REPO/migrations/config"
# schema of the full old chain (exclude sqlx's bookkeeping table)
docker exec "$c1" pg_dump -U vantage -d vantage_config --schema-only --no-owner --no-privileges --no-comments --exclude-table=_sqlx_migrations \
  | grep -vE '^\\' > "$STAGE/cfg_schema_old.sql"
docker exec "$c1" pg_dump -U vantage -d vantage_config --data-only --inserts --no-owner --exclude-table=_sqlx_migrations \
  | grep -vE '^\\' > "$STAGE/cfg_seed.sql"
# candidate 0001 = schema + seed
{ echo "-- Config DB consolidated schema (squashed for v3 GA). Generated by scripts/squash-migrations.sh."; echo;
  cat "$STAGE/cfg_schema_old.sql"; echo; echo "-- seed data"; cat "$STAGE/cfg_seed.sql"; } > "$STAGE/config_0001.sql"
# verify: apply candidate to a fresh DB, re-dump schema, must match
c2=$(start_pg "$CFG_IMG" vantage_config)
apply "$c2" vantage_config "$STAGE/config_0001.sql"
docker exec "$c2" pg_dump -U vantage -d vantage_config --schema-only --no-owner --no-privileges --no-comments --exclude-table=_sqlx_migrations \
  | grep -vE '^\\' > "$STAGE/cfg_schema_new.sql"
if diff -u "$STAGE/cfg_schema_old.sql" "$STAGE/cfg_schema_new.sql" > "$STAGE/cfg.diff"; then
  echo "  ✓ config schema reproduced exactly ($(grep -c 'CREATE TABLE' "$STAGE/config_0001.sql") tables)"
else
  echo "  ✗ config schema DIFF — aborting:"; head -40 "$STAGE/cfg.diff"; exit 1
fi

echo "════════ DATA DB ════════"
snap() { # <cid>
  local cid="$1"
  { echo "# columns"; docker exec "$cid" psql -tAqX -U vantage -d vantage_data -c \
      "SELECT table_name||'.'||column_name||' '||data_type||' '||is_nullable||' '||coalesce(column_default,'') FROM information_schema.columns WHERE table_schema='public' ORDER BY 1";
    echo "# indexes"; docker exec "$cid" psql -tAqX -U vantage -d vantage_data -c \
      "SELECT indexdef FROM pg_indexes WHERE schemaname='public' ORDER BY 1";
    echo "# hypertables"; docker exec "$cid" psql -tAqX -U vantage -d vantage_data -c \
      "SELECT hypertable_name FROM timescaledb_information.hypertables ORDER BY 1"; }
}
d1=$(start_pg "$TS_IMG" vantage_data); apply "$d1" vantage_data "$REPO/migrations/data"; snap "$d1" > "$STAGE/data_old.txt"
d2=$(start_pg "$TS_IMG" vantage_data); apply "$d2" vantage_data "$DATA_STAGED";           snap "$d2" > "$STAGE/data_new.txt"
if diff -u "$STAGE/data_old.txt" "$STAGE/data_new.txt" > "$STAGE/data.diff"; then
  echo "  ✓ data schema (columns/indexes/hypertables) identical old-vs-new"
else
  echo "  ✗ data schema DIFF — aborting:"; cat "$STAGE/data.diff"; exit 1
fi

echo "════════ SWAP (both verified) ════════"
rm -f "$REPO"/migrations/config/*.sql
cp "$STAGE/config_0001.sql" "$REPO/migrations/config/0001_init.sql"
rm -f "$REPO"/migrations/data/*.sql
cp "$DATA_STAGED" "$REPO/migrations/data/0001_init.sql"
echo "  swapped → migrations/config/0001_init.sql + migrations/data/0001_init.sql"
echo "PASS — migrations squashed. Now run the check scripts to confirm sqlx applies them."
