-- Config DB consolidated schema (squashed for v3 GA). Generated by scripts/squash-migrations.sh.

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 16.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: monitor_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.monitor_kind AS ENUM (
    'http',
    'tcp',
    'ping',
    'keyword',
    'postgres',
    'redis',
    'dns',
    'rabbitmq',
    'mysql',
    'mongodb',
    'tls',
    'push'
);


--
-- Name: ws_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.ws_role AS ENUM (
    'owner',
    'editor',
    'viewer'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alert_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_channels (
    alert_id uuid NOT NULL,
    channel_id uuid NOT NULL
);


--
-- Name: alert_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_events (
    id bigint NOT NULL,
    alert_id uuid NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    firing boolean NOT NULL,
    message text
);


--
-- Name: alert_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.alert_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: alert_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.alert_events_id_seq OWNED BY public.alert_events.id;


--
-- Name: alert_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_state (
    alert_id uuid NOT NULL,
    firing boolean DEFAULT false NOT NULL,
    last_changed timestamp with time zone DEFAULT now() NOT NULL,
    last_notified timestamp with time zone
);


--
-- Name: alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alerts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    monitor_id uuid,
    system_id uuid,
    condition jsonb DEFAULT '{}'::jsonb NOT NULL,
    cooldown_secs integer DEFAULT 300 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    renotify_secs integer,
    scope_kind text,
    scope_workspace_id uuid,
    CONSTRAINT alerts_target_ck CHECK (((monitor_id IS NOT NULL) OR (system_id IS NOT NULL) OR ((scope_kind IS NOT NULL) AND (scope_workspace_id IS NOT NULL))))
);


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    name text NOT NULL,
    key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: api_pats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_pats (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    token_hash text NOT NULL,
    prefix text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used timestamp with time zone,
    expires_at timestamp with time zone
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    user_email text,
    method text NOT NULL,
    path text NOT NULL,
    status integer NOT NULL,
    object_name text
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;


--
-- Name: channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.channels (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    name text NOT NULL,
    kind text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: exec_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exec_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    system_id uuid,
    system_name text NOT NULL,
    workspace_id uuid,
    user_id uuid,
    user_email text NOT NULL,
    transport text NOT NULL,
    ssh_user text,
    client_ip text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    status text DEFAULT 'active'::text NOT NULL,
    error text
);


--
-- Name: exec_transcript; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exec_transcript (
    session_id uuid NOT NULL,
    seq integer NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    stream text NOT NULL,
    data bytea NOT NULL
);


--
-- Name: memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memberships (
    user_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    role public.ws_role NOT NULL,
    can_exec boolean DEFAULT false NOT NULL
);


--
-- Name: monitor_debug; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitor_debug (
    monitor_id uuid NOT NULL,
    outcome text NOT NULL,
    detail jsonb NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: monitors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitors (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    name text NOT NULL,
    kind public.monitor_kind NOT NULL,
    target text NOT NULL,
    interval_secs integer DEFAULT 60 NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    token text NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ssh_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ssh_keys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    key_enc bytea NOT NULL,
    kdf_salt bytea,
    key_fingerprint text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    enc_ver smallint DEFAULT 1 NOT NULL
);


--
-- Name: status_pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status_pages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    slug text NOT NULL,
    title text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_public boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: systems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.systems (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    workspace_id uuid NOT NULL,
    key_id uuid NOT NULL,
    name text NOT NULL,
    hostname text NOT NULL,
    kind text DEFAULT 'node'::text NOT NULL,
    cluster text,
    enabled boolean DEFAULT true NOT NULL,
    last_seen timestamp with time zone,
    kernel text,
    cpu_model text,
    cpu_cores integer,
    agent_version text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    ssh_host text,
    ssh_port integer DEFAULT 22 NOT NULL,
    k8s_version text
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    read_all boolean DEFAULT false NOT NULL,
    master_key_enc bytea,
    master_key_salt bytea,
    app_kid text,
    totp_secret_enc bytea,
    totp_kid text,
    totp_enabled boolean DEFAULT false NOT NULL,
    totp_backup_codes text,
    totp_last_step bigint DEFAULT 0 NOT NULL
);


--
-- Name: webauthn_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webauthn_credentials (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    cred_id bytea NOT NULL,
    cred_data bytea NOT NULL,
    sign_count bigint DEFAULT 0 NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used timestamp with time zone
);


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    thresholds jsonb
);


--
-- Name: alert_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_events ALTER COLUMN id SET DEFAULT nextval('public.alert_events_id_seq'::regclass);


--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);


--
-- Name: alert_channels alert_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_channels
    ADD CONSTRAINT alert_channels_pkey PRIMARY KEY (alert_id, channel_id);


--
-- Name: alert_events alert_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_pkey PRIMARY KEY (id);


--
-- Name: alert_state alert_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_state
    ADD CONSTRAINT alert_state_pkey PRIMARY KEY (alert_id);


--
-- Name: alerts alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_key UNIQUE (key);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: api_pats api_pats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_pats
    ADD CONSTRAINT api_pats_pkey PRIMARY KEY (id);


--
-- Name: api_pats api_pats_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_pats
    ADD CONSTRAINT api_pats_token_hash_key UNIQUE (token_hash);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: channels channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channels_pkey PRIMARY KEY (id);


--
-- Name: exec_sessions exec_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_sessions
    ADD CONSTRAINT exec_sessions_pkey PRIMARY KEY (id);


--
-- Name: exec_transcript exec_transcript_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_transcript
    ADD CONSTRAINT exec_transcript_pkey PRIMARY KEY (session_id, seq);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (user_id, workspace_id);


--
-- Name: monitor_debug monitor_debug_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_debug
    ADD CONSTRAINT monitor_debug_pkey PRIMARY KEY (monitor_id, outcome);


--
-- Name: monitors monitors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT monitors_pkey PRIMARY KEY (id);


--
-- Name: workspaces namespaces_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT namespaces_name_key UNIQUE (name);


--
-- Name: workspaces namespaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT namespaces_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (token);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- Name: ssh_keys ssh_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ssh_keys
    ADD CONSTRAINT ssh_keys_pkey PRIMARY KEY (id);


--
-- Name: ssh_keys ssh_keys_user_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ssh_keys
    ADD CONSTRAINT ssh_keys_user_id_name_key UNIQUE (user_id, name);


--
-- Name: status_pages status_pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status_pages
    ADD CONSTRAINT status_pages_pkey PRIMARY KEY (id);


--
-- Name: status_pages status_pages_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status_pages
    ADD CONSTRAINT status_pages_slug_key UNIQUE (slug);


--
-- Name: systems systems_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.systems
    ADD CONSTRAINT systems_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: webauthn_credentials webauthn_credentials_cred_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webauthn_credentials
    ADD CONSTRAINT webauthn_credentials_cred_id_key UNIQUE (cred_id);


--
-- Name: webauthn_credentials webauthn_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webauthn_credentials
    ADD CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id);


--
-- Name: audit_log_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_at_idx ON public.audit_log USING btree (at DESC);


--
-- Name: idx_alert_events_alert; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alert_events_alert ON public.alert_events USING btree (alert_id, at DESC);


--
-- Name: idx_alert_events_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alert_events_at ON public.alert_events USING btree (at DESC);


--
-- Name: idx_api_pats_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_pats_user ON public.api_pats USING btree (user_id);


--
-- Name: idx_audit_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_at ON public.audit_log USING btree (at DESC);


--
-- Name: idx_exec_sessions_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exec_sessions_started ON public.exec_sessions USING btree (started_at DESC);


--
-- Name: idx_exec_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exec_sessions_status ON public.exec_sessions USING btree (status);


--
-- Name: idx_exec_sessions_workspace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exec_sessions_workspace ON public.exec_sessions USING btree (workspace_id);


--
-- Name: idx_monitors_workspace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_monitors_workspace ON public.monitors USING btree (workspace_id);


--
-- Name: idx_sessions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_user ON public.sessions USING btree (user_id);


--
-- Name: idx_ssh_keys_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ssh_keys_user ON public.ssh_keys USING btree (user_id);


--
-- Name: idx_systems_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_systems_kind ON public.systems USING btree (kind);


--
-- Name: idx_systems_workspace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_systems_workspace ON public.systems USING btree (workspace_id);


--
-- Name: idx_webauthn_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_webauthn_user ON public.webauthn_credentials USING btree (user_id);


--
-- Name: systems_ws_host; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX systems_ws_host ON public.systems USING btree (workspace_id, hostname);


--
-- Name: alert_channels alert_channels_alert_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_channels
    ADD CONSTRAINT alert_channels_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alerts(id) ON DELETE CASCADE;


--
-- Name: alert_channels alert_channels_channel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_channels
    ADD CONSTRAINT alert_channels_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE;


--
-- Name: alert_events alert_events_alert_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alerts(id) ON DELETE CASCADE;


--
-- Name: alert_state alert_state_alert_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_state
    ADD CONSTRAINT alert_state_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alerts(id) ON DELETE CASCADE;


--
-- Name: alerts alerts_monitor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_monitor_id_fkey FOREIGN KEY (monitor_id) REFERENCES public.monitors(id) ON DELETE CASCADE;


--
-- Name: alerts alerts_scope_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_scope_namespace_id_fkey FOREIGN KEY (scope_workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: alerts alerts_system_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alerts
    ADD CONSTRAINT alerts_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id) ON DELETE CASCADE;


--
-- Name: api_keys api_keys_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: api_pats api_pats_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_pats
    ADD CONSTRAINT api_pats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: channels channels_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channels_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: exec_sessions exec_sessions_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_sessions
    ADD CONSTRAINT exec_sessions_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE SET NULL;


--
-- Name: exec_sessions exec_sessions_system_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_sessions
    ADD CONSTRAINT exec_sessions_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(id) ON DELETE SET NULL;


--
-- Name: exec_sessions exec_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_sessions
    ADD CONSTRAINT exec_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: exec_transcript exec_transcript_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exec_transcript
    ADD CONSTRAINT exec_transcript_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.exec_sessions(id) ON DELETE CASCADE;


--
-- Name: memberships memberships_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: memberships memberships_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: monitor_debug monitor_debug_monitor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_debug
    ADD CONSTRAINT monitor_debug_monitor_id_fkey FOREIGN KEY (monitor_id) REFERENCES public.monitors(id) ON DELETE CASCADE;


--
-- Name: monitors monitors_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT monitors_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: ssh_keys ssh_keys_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ssh_keys
    ADD CONSTRAINT ssh_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: status_pages status_pages_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status_pages
    ADD CONSTRAINT status_pages_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: systems systems_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.systems
    ADD CONSTRAINT systems_key_id_fkey FOREIGN KEY (key_id) REFERENCES public.api_keys(id) ON DELETE CASCADE;


--
-- Name: systems systems_namespace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.systems
    ADD CONSTRAINT systems_namespace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: webauthn_credentials webauthn_credentials_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webauthn_credentials
    ADD CONSTRAINT webauthn_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


-- seed data
--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 16.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: workspaces; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.workspaces VALUES ('9454a4fb-239b-4f3c-b5a7-b91b569b4ba0', 'default', '2026-07-09 03:11:07.187153+00', NULL);


--
-- Data for Name: api_keys; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: monitors; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: systems; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: alerts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: channels; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: alert_channels; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: alert_events; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: alert_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: api_pats; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exec_sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exec_transcript; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: memberships; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: monitor_debug; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.settings VALUES ('data_cap_limit_bytes', '10737418240', '2026-07-09 03:11:08.837491+00');
INSERT INTO public.settings VALUES ('data_cap_enabled', 'false', '2026-07-09 03:11:08.837491+00');
INSERT INTO public.settings VALUES ('exec_transcript_retention_days', '30', '2026-07-09 03:11:08.839725+00');
INSERT INTO public.settings VALUES ('alert_events_retention_days', '365', '2026-07-09 03:11:08.839725+00');
INSERT INTO public.settings VALUES ('exec_sessions_retention_days', '365', '2026-07-09 03:11:08.839725+00');
INSERT INTO public.settings VALUES ('sessions_retention_days', '14', '2026-07-09 03:11:08.839725+00');


--
-- Data for Name: ssh_keys; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: status_pages; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: webauthn_credentials; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: alert_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.alert_events_id_seq', 1, false);


--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--

